### ISSUE TITLE
Change in routing breaks old links

### ISSUE THREAD

**Issue by t4ccer** [cardano-foundation/cf-cip-frontend#20]
Quite recently URLs changed from `cips.cardano.org/cips/cipXX` to `cips.cardano.org/cip/CIP-XXXX` (e.g. https://cips.cardano.org/cips/cip30/ is now at https://cips.cardano.org/cip/CIP-0030) and it broke all links to CIPs on external websites and documentations.

Can this be reverted, or at least redirects set up to the new URLs?

**Comment by Ryun1** [comment]
+1 on this  😎

**Comment by rphair** [comment]
+2 (cumulative) 🤓

**Comment by t4ccer** [comment]
Yep, both link formats work now, thanks!
