### ISSUE TITLE
[Bug] Website not showing latest changes to CIP

### ISSUE THREAD

**Issue by Ryun1** [cardano-foundation/cf-cip-frontend#33]
- The CIP-69 rendered on https://cips.cardano.org/cip/CIP-0069 does not match the text shown via [CIPs/CIP-0069](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0069)
- It seems that https://cips.cardano.org/cip/CIP-0069 is not showing the most recent commit of [93a6c22](https://github.com/cardano-foundation/CIPs/commit/93a6c226d608f29d4651ae435a4d7557f18d8b10) and is just showing the only commit before ([ece5ee5](ece5ee5e1011e1798906047f2da1d0d6a5a8e2d9))
- Im not sure if this is happening for other proposals also

Spotted by @ch1bo 🤝

**Comment by aldo555** [comment]
Assuming we can also close this one since the build fail issue was fixed. @rphair ?

**Comment by rphair** [comment]
yes, I was just here commenting to say that :) cc @Ryun1
