### ISSUE TITLE
[Bug] Netlify build fails, site content is obsolete

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/cf-cip-frontend#36]
Encompasses https://github.com/cardano-foundation/cf-cip-frontend/issues/33 although the problem is more general.

Noticed when merging https://github.com/cardano-foundation/cf-cip-frontend/pull/35 into `master` did not update the site content. Reports a Netlify build failure with no details (that I can tell) beyond the build script exiting with a non-zero status: https://app.netlify.com/sites/cips/deploys/66ea2882f7d7d800083f0aa9?deploy_diagnostics=true

**Impact on community is substantial**: for instance CIP-1694, the subject of much community & media attention, is still showing `Proposed` rather than `Active`: https://cips.cardano.org/cip/CIP-1694 (vs. source content https://github.com/cardano-foundation/CIPs/blob/master/CIP-1694/README.md).

This affects not only CIP content but also changes to site parameters, as requested in https://github.com/cardano-foundation/cf-cip-frontend/pull/34 (cc @Ryun1 @perturbing).

cc @ptrdsh @aldo555 @KtorZ

**Comment by aldo555** [comment]
Issue has been fixed and the latest version is now live. Issue was an expired token.
